// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Hero: typeof import('./components/Home/Hero/index.vue')['default']
    Navbar: typeof import('./components/Home/Navbar/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
